title: pamaworks site
email: sycop78@gmail.com
description: >- # 1lin "baseurl:"
  좋은 사이트가 
  되어야할듯
baseurl : ""
url : pamaworks.github.io
twitter_username:
github_username:  pamaworks

theme: minima
plugins:
  - jekyll-feed